## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [2]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [3]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[["Attrition", "Department"]]

In [4]:
# Create a list of at least 10 column names to use as X data
X_columns = ["Age", "Education", "HourlyRate", "JobInvolvement", "StockOptionLevel", "TotalWorkingYears", "YearsAtCompany", "YearsInCurrentRole", "YearsSinceLastPromotion", "NumCompaniesWorked"]


# Create X_df using your selected columns
X_df = attrition_df[X_columns]

# Show the data types for X_df
X_df.dtypes


Age                        int64
Education                  int64
HourlyRate                 int64
JobInvolvement             int64
StockOptionLevel           int64
TotalWorkingYears          int64
YearsAtCompany             int64
YearsInCurrentRole         int64
YearsSinceLastPromotion    int64
NumCompaniesWorked         int64
dtype: object

In [5]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.2, random_state=42)

In [ ]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary


In [6]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
X_scaler = scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


In [7]:
from sklearn.preprocessing import OneHotEncoder
# Create a OneHotEncoder for the Department column
department_encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
department_encoder.fit(y_train[['Department']])

# Create two new variables by applying the encoder
# to the training and testing data
department_train_encoded = department_encoder.transform(y_train[["Department"]])
department_test_encoded = department_encoder.transform(y_test[["Department"]])

print(department_train_encoded)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# Create a OneHotEncoder for the Attrition column
attrition_encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
attrition_encoder.fit(y_train[['Attrition']])

# Create two new variables by applying the encoder
# to the training and testing data
attrition_train_encoded = attrition_encoder.transform(y_train[["Attrition"]])
attrition_test_encoded = attrition_encoder.transform(y_test[["Attrition"]])

print(attrition_train_encoded)


[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [1. 0.]
 [1. 0.]]


## Create, Compile, and Train the Model

In [9]:
print(X_train.shape)

(1176, 10)


In [10]:
# Find the number of columns in the X training data
input_nodes = len(X_train.columns)

# Create the input layer
input_layer = layers.Input(shape=(X_train.shape[1],), name="input_layer")

# Create at least two shared layers
shared_layer1 = layers.Dense(64, activation="relu", name="shared1")(input_layer)
shared_layer2 = layers.Dense(128, activation="relu", name="shared2")(shared_layer1)


In [11]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
department_hidden_layer = layers.Dense(32,
                                       activation="relu",
                                       name="department_hidden")(shared_layer2)

# Create the output layer
department_output_layer = layers.Dense(3,
                                       activation="sigmoid",
                                       name="department_output")(department_hidden_layer)


In [12]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
attrition_hidden_layer = layers.Dense(32,
                                      activation="relu",
                                      name="attrition_hidden")(shared_layer2)

# Create the output layer
attrition_output_layer = layers.Dense(2,
                                      activation="softmax",
                                      name="attrition_output")(attrition_hidden_layer)



In [13]:
# Create the model
model = Model(inputs=input_layer, outputs=[
    department_output_layer,
    attrition_output_layer
])

# Compile the model
model.compile(optimizer="adam",
              loss={
                  "department_output": "binary_crossentropy",
                  "attrition_output": "binary_crossentropy"
              },
              metrics={
                  "department_output": "accuracy",
                  "attrition_output": "accuracy"
              })

# Summarize the model
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_layer (InputLayer)    [(None, 10)]                 0         []                            
                                                                                                  
 shared1 (Dense)             (None, 64)                   704       ['input_layer[0][0]']         
                                                                                                  
 shared2 (Dense)             (None, 128)                  8320      ['shared1[0][0]']             
                                                                                                  
 department_hidden (Dense)   (None, 32)                   4128      ['shared2[0][0]']             
                                                                                              

In [14]:
# Train the model
model.fit(
    X_train_scaled,
    {
        'department_output': department_train_encoded,
        'attrition_output': attrition_train_encoded
    },
    epochs=10,
    batch_size=32,
    validation_split=0.2
)


Epoch 1/10
30/30 [==============================] - 2s 16ms/step - loss: 1.1304 - department_output_loss: 0.5572 - attrition_output_loss: 0.5732 - department_output_accuracy: 0.6479 - attrition_output_accuracy: 0.7596 - val_loss: 1.0075 - val_department_output_loss: 0.5069 - val_attrition_output_loss: 0.5006 - val_department_output_accuracy: 0.6314 - val_attrition_output_accuracy: 0.7966
Epoch 2/10
30/30 [==============================] - 0s 4ms/step - loss: 0.9302 - department_output_loss: 0.4824 - attrition_output_loss: 0.4478 - department_output_accuracy: 0.6553 - attrition_output_accuracy: 0.8404 - val_loss: 0.9895 - val_department_output_loss: 0.5008 - val_attrition_output_loss: 0.4886 - val_department_output_accuracy: 0.6314 - val_attrition_output_accuracy: 0.7966
Epoch 3/10
30/30 [==============================] - 0s 5ms/step - loss: 0.9077 - department_output_loss: 0.4786 - attrition_output_loss: 0.4291 - department_output_accuracy: 0.6553 - attrition_output_accuracy: 0.8404 - 

In [15]:
# Evaluate the model with the testing data
results = model.evaluate(X_test_scaled, {
        "department_output": department_test_encoded,
        "attrition_output": attrition_test_encoded
    })

10/10 [==============================] - 0s 3ms/step - loss: 0.8761 - department_output_loss: 0.4739 - attrition_output_loss: 0.4022 - department_output_accuracy: 0.6667 - attrition_output_accuracy: 0.8503


In [16]:
print(results)

[0.8761053681373596, 0.4739204943180084, 0.40218496322631836, 0.6666666865348816, 0.8503401279449463]


In [17]:
# Print the accuracy for both department and attrition
pred_categories = ["Department", "Attrition"]
for i, cat in enumerate(pred_categories):
    print(f"{i}-{cat} predictions accuracy: {results[i+3]}")

0-Department predictions accuracy: 0.6666666865348816
1-Attrition predictions accuracy: 0.8503401279449463


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1.
2.
3.